import type { ArticleCoverVariant, ArticleDiagramVariant } from "@/lib/media";
import type { ArticleNoteType } from "./article-types";

export type ArticleContentPlan = {
  slug: string;
  noteType: ArticleNoteType;
  plannedTitle: string;
  hook: string;
  outline: string[];
  targetReadMinutes: number;
  coverVariant: ArticleCoverVariant;
  diagramVariants: ArticleDiagramVariant[];
  needsCodeExample: boolean;
  needsReferences: boolean;
};

export const articleContentPlans: ArticleContentPlan[] = [
  {
    slug: "top-10-things-i-would-do-if-i-were-starting-again-as-a-junior-developer",
    noteType: "Field Notes",
    plannedTitle: "Starting Again as a Junior Developer",
    hook: "I once shipped a feature I could not trace through the stack.",
    outline: [
      "Hook: early-career mistake with HTTP and debugging",
      "Context: tutorial loop vs finishing small systems",
      "Problem: exposure felt like competence",
      "What I learned: fundamentals and git beat more courses",
      "Example: one debug session write-up",
      "Takeaway: finish small loops before chasing breadth",
    ],
    targetReadMinutes: 3,
    coverVariant: "field",
    diagramVariants: [],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "developing-scalable-solutions-for-ghanaian-users-as-a-secure-software-lifecycle-professional",
    noteType: "Product Notes",
    plannedTitle: "Building for Ghanaian Users",
    hook: "A payment looked successful on screen. The wallet never updated.",
    outline: [
      "Hook: timeout on a mobile money flow",
      "Context: fintech work in Ghana",
      "Problem: happy-path design on bad networks",
      "What I learned: idempotency and clear states are UX",
      "Example: retry key and status payload",
      "Takeaway: design for the network you have",
    ],
    targetReadMinutes: 3,
    coverVariant: "product-ghana",
    diagramVariants: ["network"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "structuring-large-flutter-applications-using-clean-architecture",
    noteType: "Engineering Notes",
    plannedTitle: "Flutter Apps That Stay Readable",
    hook: "The app was fine at three screens. It broke at twelve.",
    outline: [
      "Hook: boundary creep on a growing Flutter app",
      "Context: mobile product with multiple integrations",
      "Problem: UI started calling data directly",
      "What I learned: thin screens and clear repositories",
      "Example: short Dart boundary",
      "Takeaway: add seams before the tree collapses",
    ],
    targetReadMinutes: 3,
    coverVariant: "flutter-layers",
    diagramVariants: ["layers"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "lessons-from-building-cloud-native-systems-with-nextjs-and-nestjs",
    noteType: "Architecture Notes",
    plannedTitle: "Next.js and NestJS in Production",
    hook: "The API timed out because the email job ran in the request.",
    outline: [
      "Hook: slow request path on a shipped product",
      "Context: full-stack split across web and API",
      "Problem: sync work inside HTTP handlers",
      "What I learned: split request path from background work",
      "Example: controller hands off to queue",
      "Takeaway: answer fast. process async.",
    ],
    targetReadMinutes: 3,
    coverVariant: "cloud-stack",
    diagramVariants: ["flow-horizontal"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "why-technical-leadership-is-more-than-just-writing-code",
    noteType: "Leadership Notes",
    plannedTitle: "Leadership Beyond Code",
    hook: "The sprint failed with green CI and merged PRs.",
    outline: [
      "Hook: unclear API contract across teams",
      "Context: lead role on a delivery push",
      "Problem: coding was fine. clarity was missing.",
      "What I learned: ownership starts before the sprint",
      "Takeaway: make success visible early",
    ],
    targetReadMinutes: 2,
    coverVariant: "leadership",
    diagramVariants: ["workshop"],
    needsCodeExample: true,
    needsReferences: false,
  },
  {
    slug: "how-to-design-api-endpoints-that-stay-small-predictable-and-easy-to-test",
    noteType: "Engineering Notes",
    plannedTitle: "API Endpoints That Stay Small",
    hook: "One route handled validation, mapping, and side effects.",
    outline: [
      "Hook: endpoint grew until tests were useless",
      "Context: backend service under feature pressure",
      "Problem: handler did too many jobs",
      "What I learned: one job per endpoint",
      "Example: thin handler shape",
      "Takeaway: if you cannot describe it in one sentence, split it",
    ],
    targetReadMinutes: 3,
    coverVariant: "api-flow",
    diagramVariants: ["flow-horizontal"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-structure-a-react-frontend-so-ui-data-and-state-do-not-collide",
    noteType: "Engineering Notes",
    plannedTitle: "React Without Tangled State",
    hook: "The screen fetched the same data three times on mount.",
    outline: [
      "Hook: duplicate requests in one view",
      "Context: React feature with shared data",
      "Problem: state ownership was unclear",
      "What I learned: separate render from data orchestration",
      "Example: feature folder boundary",
      "Takeaway: name the owner of each piece of state",
    ],
    targetReadMinutes: 2,
    coverVariant: "react-state",
    diagramVariants: ["layers"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-debug-a-production-incident-without-guessing",
    noteType: "Field Notes",
    plannedTitle: "Debugging Production Without Guessing",
    hook: "Alerts fired. The dashboard looked fine.",
    outline: [
      "Hook: wrong first assumption during an incident",
      "Context: production issue under time pressure",
      "Problem: team wanted to patch before isolating",
      "What I learned: observe, isolate, verify, then change",
      "Example: short incident timeline",
      "Takeaway: evidence beats speed without proof",
    ],
    targetReadMinutes: 2,
    coverVariant: "incident",
    diagramVariants: ["pipeline"],
    needsCodeExample: true,
    needsReferences: false,
  },
  {
    slug: "how-to-build-offline-first-mobile-features-for-unstable-networks",
    noteType: "Product Notes",
    plannedTitle: "Offline-First on Bad Networks",
    hook: "The user tapped save. The network dropped before the response.",
    outline: [
      "Hook: lost form state on a flaky connection",
      "Context: mobile feature in a low-bandwidth market",
      "Problem: UI pretended the network was reliable",
      "What I learned: protect user intent first",
      "Example: optimistic write queue",
      "Takeaway: show pending state honestly",
    ],
    targetReadMinutes: 2,
    coverVariant: "offline",
    diagramVariants: ["network"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-refactor-a-monolith-into-clearer-modules-without-breaking-everything",
    noteType: "Architecture Notes",
    plannedTitle: "Refactoring a Monolith Safely",
    hook: "We needed a seam, not a rewrite.",
    outline: [
      "Hook: risky refactor request before a release",
      "Context: monolith with mixed domains",
      "Problem: team wanted big-bang extraction",
      "What I learned: find the seam with tests",
      "Example: before and after import boundary",
      "Takeaway: ship while you split",
    ],
    targetReadMinutes: 2,
    coverVariant: "monolith",
    diagramVariants: ["layers"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-set-up-a-practical-ci-pipeline-that-catches-regressions-early",
    noteType: "Engineering Notes",
    plannedTitle: "CI That Catches Regressions Early",
    hook: "A green merge still broke production on Tuesday.",
    outline: [
      "Hook: missing check in a noisy pipeline",
      "Context: team shipping several times a week",
      "Problem: CI was slow and ignored",
      "What I learned: fastest useful check first",
      "Example: minimal workflow file",
      "Takeaway: CI should build trust, not fatigue",
    ],
    targetReadMinutes: 2,
    coverVariant: "ci-pipeline",
    diagramVariants: ["pipeline"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-build-a-feature-team-feedback-loop-with-logging-metrics-and-alerts",
    noteType: "Field Notes",
    plannedTitle: "When Metrics Looked Fine",
    hook: "The feature chart was green. Support tickets were not.",
    outline: [
      "Hook: silent user failures after release",
      "Context: feature team with basic metrics",
      "Problem: success metric missed real failures",
      "What I learned: instrument the workflow users care about",
      "Example: one log and metric contract",
      "Takeaway: close the loop with product, not only engineering",
    ],
    targetReadMinutes: 2,
    coverVariant: "observability",
    diagramVariants: ["flow-horizontal"],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-document-engineering-decisions-so-the-team-can-move-faster",
    noteType: "Leadership Notes",
    plannedTitle: "One Note Ended Three Meetings",
    hook: "We debated the same decision in three meetings.",
    outline: [
      "Hook: recurring architecture argument",
      "Context: growing team and shifting constraints",
      "Problem: decisions lived in chat threads",
      "What I learned: context beats conclusion alone",
      "Example: eight-line decision note",
      "Takeaway: write it once. point people to it.",
    ],
    targetReadMinutes: 2,
    coverVariant: "documentation",
    diagramVariants: [],
    needsCodeExample: true,
    needsReferences: true,
  },
  {
    slug: "how-to-use-ai-tools-in-a-software-workflow-without-losing-engineering-judgment",
    noteType: "Engineering Notes",
    plannedTitle: "AI in the Workflow",
    hook: "The generated code passed review. It failed on a null edge case.",
    outline: [
      "Hook: plausible AI output with a hidden bug",
      "Context: using AI for repetitive implementation",
      "Problem: speed without verification",
      "What I learned: AI assists. you still own the proof.",
      "Example: short review checklist",
      "Takeaway: verify like any untrusted input",
    ],
    targetReadMinutes: 2,
    coverVariant: "ai-workflow",
    diagramVariants: [],
    needsCodeExample: true,
    needsReferences: false,
  },
  {
    slug: "how-to-plan-and-run-a-technical-architecture-workshop-that-actually-helps",
    noteType: "Architecture Notes",
    plannedTitle: "Architecture Workshops That Decide",
    hook: "One workshop ended in opinions. The next ended with an owner.",
    outline: [
      "Hook: two workshops, different outcomes",
      "Context: team stuck on a design choice",
      "Problem: no decision artifact",
      "What I learned: outcome before the room fills",
      "Example: one-page workshop output",
      "Takeaway: leave with one next step",
    ],
    targetReadMinutes: 2,
    coverVariant: "workshop",
    diagramVariants: ["workshop"],
    needsCodeExample: true,
    needsReferences: true,
  },
];

const contentPlanBySlug = new Map(
  articleContentPlans.map((plan) => [plan.slug, plan]),
);

export function getArticleContentPlan(slug: string) {
  return contentPlanBySlug.get(slug);
}

export function getContentPlanByNoteType(noteType: ArticleNoteType) {
  return articleContentPlans.filter((plan) => plan.noteType === noteType);
}
